version: '2.1'
services:
  docker-1:
    build: ./docker-1
    privileged: true
    restart: always
    labels:
      io.balena.features.balena-socket: '1'
  docker-2:
    build: ./docker-2
    privileged: true
    restart: always
    labels:
      io.balena.features.balena-socket: '1'
